CREATE TABLE SOCCER_TEAMS(
  TEAM_ID BIGINT PRIMARY KEY,
  TEAM_NAME VARCHAR(20)
);

CREATE TABLE SOCCER_LEAGUE(
  TEAM_ID BIGINT PRIMARY KEY,
  TEAM_SCORE INTEGER
);

CREATE TABLE MATCHES(
  MATCH_ID BIGINT PRIMARY KEY,
  HOME_ID BIGINT,
  AWAY_ID BIGINT,
  HOME_SCORE INTEGER,
  AWAY_SCORE INTEGER
);